### ISSUE TITLE
Knative install issues

### ISSUE THREAD

**Issue by mklumpen** [csantanapr/knative-minikube#14]
Instructions were very helpful. I followed this for installing on Docker Desktop on Windows by running commands in wsl bash shell and ran into the following issues:
1. EXTERNAL_IP was getting set to localhost with the command in step 5. Setting to 127.0.01 explicitly resolves the issue.
2. In the commands below the serving-domainmapping files were not found, but I was still able to send the event successfully:
kubectl apply -f https://github.com/knative/serving/releases/download/v$KNATIVE_VERSION/serving-domainmapping-crds.yaml
kubectl wait --for=condition=Established --all crd
kubectl apply -f https://github.com/knative/serving/releases/download/v$KNATIVE_VERSION/serving-domainmapping.yaml

**Comment by csantanapr** [comment]
thank you for opening this issue, I will take a look

**Comment by csantanapr** [comment]
If someone has a windows machine and want to help troubleshoot what's going, or update the script to do it differently on windows than linux/macos also would be appreciated

**Comment by csantanapr** [comment]
domain mapping files are not need it anymore
