### ISSUE TITLE
Install Knative Eventing instructions issue -server reported 404 Not Found 

### ISSUE THREAD

**Issue by boukisge** [csantanapr/knative-minikube#19]
**Install Knative DomainMapping**

Georges-iMac:~ gboukis$ kubectl apply -f https://github.com/knative/serving/releases/download/v$KNATIVE_VERSION/serving-domainmapping-crds.yaml

error: unable to read URL "https://github.com/knative/serving/releases/download/v1.0.0/serving-domainmapping-crds.yaml", server reported 404 Not Found, status code=404

**Comment by csantanapr** [comment]
Good catch we don't need to install domain mapping separately now is part of serving.
But we need to add instructions for ClusterDomain creation

**Comment by boukisge** [comment]
Let me know , when it’s updated or you can send separate instructions via
email and I will give it a go

Thank You

**Comment by boukisge** [comment]
Got it, thanks!
