### ISSUE TITLE
Not seeing resources

### ISSUE THREAD

**Issue by pjiocnic** [csantanapr/knative-minikube#7]
While your example works for me and I'm able to see the pods scaling up and down, why is that I don't see any output from

kubectl get pods -n knative-eventing
kubectl get pods -n knative-sources
kubectl get pods -n knative-monitoring

I'm new to knative so I might be missing the obvious

Thank you,

**Comment by csantanapr** [comment]
don't know maybe you change your kubectl context and targeting another cluster
