### ISSUE TITLE
Instructions not working on Windows

### ISSUE THREAD

**Issue by Spenhouet** [csantanapr/knative-minikube#8]
Remarks:

1. For the install of minikube the Windows equivalent is:

```
winget install minikube
```

2. All the `export` commands do not work on Windows.
I typed in the version into the URLs.

3. The URL for Kourier changed

It changed from https://github.com/knative/net-kourier to https://github.com/knative-sandbox/net-kourier.

4. For me the following does not return anything:

```
kubectl -n kourier-system get service kourier -o jsonpath='{.status.loadBalancer.ingress[0].ip}')
```

5. The new line breaks in the following command do not work on Windows. This will execute line by line.

```
kubectl patch configmap/config-network \
  --namespace knative-serving \
  --type merge \
  --patch '{"data":{"ingress.class":"kourier.ingress.networking.knative.dev"}}'
```

6. But even with everything in one line, this results in an error for me:

> Error from server: Invalid JSON Patch

**Comment by csantanapr** [comment]
I updated the example on PR #9 

1. For windows instructions I updated so the user need to go to minikube for instructions, I don't want to maintain minikube instructions for Linux or windows.


2 The command are intended for bash/shell Linux, On windows you can install [git-bash](https://www.educative.io/edpresso/how-to-install-git-bash-in-windows) or WSL2. but I removed the `exports` as they do not really need it.

3. The URL for Kourier changed, but the redirect is in place and this is why it still works even if we moved the repo from knative org to knative-sandbox org. But I didn't notice until you pointed it out. thanks I updated here and in [knative-kind](https://github.com/csantanapr/knative-kind)

4. For the command
```
kubectl -n kourier-system get service kourier -o jsonpath='{.status.loadBalancer.ingress[0].ip}')
```
You need to make sure you have `minikube tunnel` running in another windows and pay attention if you get prompted for a password. Also try multiple times it might take some time until is ready. I updated the instructions for user to try again and make sure they have minikube tunnel running

5. The line brakes work on Linux and MacOS, not for windows. you need to use git-bash or WSL2 on Windows. I made them one liner to be more windows friendly now

6. In windows you would need to change the single quotes and double quotes for kubectl and json patch try this
You can see this issue https://github.com/kubernetes/kubectl/issues/519 for more help on how to use json path in windows terminal or poweshell.
